package dao;
// Generated 2019-09-27 22:49:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private int numclient;
     private String nomClient;
     private String prenomClient;
     private String adresse;
     private String ville;
     private String codePostal;
     private short age;
     private String permis;
     private String courriel;
     private String telephone;
     private Set contacts = new HashSet(0);
     private Set logins = new HashSet(0);
     private Set contrats = new HashSet(0);

    public Client() {
    }

	
    public Client(int numclient, String nomClient, String prenomClient, String adresse, String ville, String codePostal, short age, String permis, String courriel, String telephone) {
        this.numclient = numclient;
        this.nomClient = nomClient;
        this.prenomClient = prenomClient;
        this.adresse = adresse;
        this.ville = ville;
        this.codePostal = codePostal;
        this.age = age;
        this.permis = permis;
        this.courriel = courriel;
        this.telephone = telephone;
    }
    public Client(int numclient, String nomClient, String prenomClient, String adresse, String ville, String codePostal, short age, String permis, String courriel, String telephone, Set contacts, Set logins, Set contrats) {
       this.numclient = numclient;
       this.nomClient = nomClient;
       this.prenomClient = prenomClient;
       this.adresse = adresse;
       this.ville = ville;
       this.codePostal = codePostal;
       this.age = age;
       this.permis = permis;
       this.courriel = courriel;
       this.telephone = telephone;
       this.contacts = contacts;
       this.logins = logins;
       this.contrats = contrats;
    }
   
    public int getNumclient() {
        return this.numclient;
    }
    
    public void setNumclient(int numclient) {
        this.numclient = numclient;
    }
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }
    public String getPrenomClient() {
        return this.prenomClient;
    }
    
    public void setPrenomClient(String prenomClient) {
        this.prenomClient = prenomClient;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getCodePostal() {
        return this.codePostal;
    }
    
    public void setCodePostal(String codePostal) {
        this.codePostal = codePostal;
    }
    public short getAge() {
        return this.age;
    }
    
    public void setAge(short age) {
        this.age = age;
    }
    public String getPermis() {
        return this.permis;
    }
    
    public void setPermis(String permis) {
        this.permis = permis;
    }
    public String getCourriel() {
        return this.courriel;
    }
    
    public void setCourriel(String courriel) {
        this.courriel = courriel;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Set getContacts() {
        return this.contacts;
    }
    
    public void setContacts(Set contacts) {
        this.contacts = contacts;
    }
    public Set getLogins() {
        return this.logins;
    }
    
    public void setLogins(Set logins) {
        this.logins = logins;
    }
    public Set getContrats() {
        return this.contrats;
    }
    
    public void setContrats(Set contrats) {
        this.contrats = contrats;
    }




}


