package dao;
// Generated 2019-09-27 22:49:48 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private int numContact;
     private Client client;
     private String message;
     private Date datemessage;
     private String sujet;

    public Contact() {
    }

    public Contact(int numContact, Client client, String message, Date datemessage, String sujet) {
       this.numContact = numContact;
       this.client = client;
       this.message = message;
       this.datemessage = datemessage;
       this.sujet = sujet;
    }
   
    public int getNumContact() {
        return this.numContact;
    }
    
    public void setNumContact(int numContact) {
        this.numContact = numContact;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getDatemessage() {
        return this.datemessage;
    }
    
    public void setDatemessage(Date datemessage) {
        this.datemessage = datemessage;
    }
    public String getSujet() {
        return this.sujet;
    }
    
    public void setSujet(String sujet) {
        this.sujet = sujet;
    }




}


