package dao;
// Generated 2019-09-27 22:49:48 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * Contrat generated by hbm2java
 */
public class Contrat implements java.io.Serializable {

    private int numContrat;
    private Client client;
    private Vehicule vehicule;
    private Date dateDepart;
    private Date dateRetourSuppose;
    private Date dateRetourEffective;
    private Date dateContrat;
    private BigDecimal caution;

    public Contrat() {
    }

    public Contrat(int numContrat, Client client, Vehicule vehicule,
            Date dateDepart, Date dateRetourSuppose, Date dateRetourEffective,
            Date dateContrat, BigDecimal caution) {
        this.numContrat = numContrat;
        this.client = client;
        this.vehicule = vehicule;
        this.dateDepart = dateDepart;
        this.dateRetourSuppose = dateRetourSuppose;
        this.dateRetourEffective = dateRetourEffective;
        this.dateContrat = dateContrat;
        this.caution = caution;
    }

    public int getNumContrat() {
        return this.numContrat;
    }

    public void setNumContrat(int numContrat) {
        this.numContrat = numContrat;
    }

    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public Vehicule getVehicule() {
        return this.vehicule;
    }

    public void setVehicule(Vehicule vehicule) {
        this.vehicule = vehicule;
    }

    public Date getDateDepart() {
        return this.dateDepart;
    }

    public void setDateDepart(Date dateDepart) {
        this.dateDepart = dateDepart;
    }

    public Date getDateRetourSuppose() {
        return this.dateRetourSuppose;
    }

    public void setDateRetourSuppose(Date dateRetourSuppose) {
        this.dateRetourSuppose = dateRetourSuppose;
    }

    public Date getDateRetourEffective() {
        return this.dateRetourEffective;
    }

    public void setDateRetourEffective(Date dateRetourEffective) {
        this.dateRetourEffective = dateRetourEffective;
    }

    public Date getDateContrat() {
        return this.dateContrat;
    }

    public void setDateContrat(Date dateContrat) {
        this.dateContrat = dateContrat;
    }

    public BigDecimal getCaution() {
        return this.caution;
    }

    public void setCaution(BigDecimal caution) {
        this.caution = caution;
    }

}
