package dao;
// Generated 2019-09-27 22:49:48 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Modele generated by hbm2java
 */
public class Modele  implements java.io.Serializable {


     private short codeModel;
     private String nomModel;
     private String marque;
     private BigDecimal puissance;
     private BigDecimal tarifJour;
     private String photo;
     private Byte nbplaces;
     private Set vehicules = new HashSet(0);

    public Modele() {
    }

	
    public Modele(short codeModel, String nomModel, String marque, BigDecimal puissance, BigDecimal tarifJour, String photo) {
        this.codeModel = codeModel;
        this.nomModel = nomModel;
        this.marque = marque;
        this.puissance = puissance;
        this.tarifJour = tarifJour;
        this.photo = photo;
    }
    public Modele(short codeModel, String nomModel, String marque, BigDecimal puissance, BigDecimal tarifJour, String photo, Byte nbplaces, Set vehicules) {
       this.codeModel = codeModel;
       this.nomModel = nomModel;
       this.marque = marque;
       this.puissance = puissance;
       this.tarifJour = tarifJour;
       this.photo = photo;
       this.nbplaces = nbplaces;
       this.vehicules = vehicules;
    }
   
    public short getCodeModel() {
        return this.codeModel;
    }
    
    public void setCodeModel(short codeModel) {
        this.codeModel = codeModel;
    }
    public String getNomModel() {
        return this.nomModel;
    }
    
    public void setNomModel(String nomModel) {
        this.nomModel = nomModel;
    }
    public String getMarque() {
        return this.marque;
    }
    
    public void setMarque(String marque) {
        this.marque = marque;
    }
    public BigDecimal getPuissance() {
        return this.puissance;
    }
    
    public void setPuissance(BigDecimal puissance) {
        this.puissance = puissance;
    }
    public BigDecimal getTarifJour() {
        return this.tarifJour;
    }
    
    public void setTarifJour(BigDecimal tarifJour) {
        this.tarifJour = tarifJour;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Byte getNbplaces() {
        return this.nbplaces;
    }
    
    public void setNbplaces(Byte nbplaces) {
        this.nbplaces = nbplaces;
    }
    public Set getVehicules() {
        return this.vehicules;
    }
    
    public void setVehicules(Set vehicules) {
        this.vehicules = vehicules;
    }




}


