package dao;
// Generated 2019-09-27 22:49:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehicule generated by hbm2java
 */
public class Vehicule  implements java.io.Serializable {


     private String matricule;
     private Modele modele;
     private String categorie;
     private boolean automatique;
     private Set contrats = new HashSet(0);

    public Vehicule() {
    }

	
    public Vehicule(String matricule, Modele modele, String categorie, boolean automatique) {
        this.matricule = matricule;
        this.modele = modele;
        this.categorie = categorie;
        this.automatique = automatique;
    }
    public Vehicule(String matricule, Modele modele, String categorie, boolean automatique, Set contrats) {
       this.matricule = matricule;
       this.modele = modele;
       this.categorie = categorie;
       this.automatique = automatique;
       this.contrats = contrats;
    }
   
    public String getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }
    public Modele getModele() {
        return this.modele;
    }
    
    public void setModele(Modele modele) {
        this.modele = modele;
    }
    public String getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(String categorie) {
        this.categorie = categorie;
    }
    public boolean isAutomatique() {
        return this.automatique;
    }
    
    public void setAutomatique(boolean automatique) {
        this.automatique = automatique;
    }
    public Set getContrats() {
        return this.contrats;
    }
    
    public void setContrats(Set contrats) {
        this.contrats = contrats;
    }




}


